### ISSUE TITLE
Only Way to Contact you.

### ISSUE THREAD

**Issue by Plebejer258** [GMagician/SAMD51-SmartEEprom-Activator#2]
Hi,
sorry for using this way to start a communication with you, but you have contributet to the Maril 2 SAMD51 implementation.
I have developed my own SAMD51 Board which use the SAMD51J19 MCU.
I have modified Marlin 2.0.4.4 to use my MCU and finaly compiled without Problem.
For testing i have a Breakout Board whit a REPRAP Discount Graphic LCD, a SD-Card reader and a I2C EEPROM attached. All othe Pins are unpopulated and open but defined in the Board File.
I using the ADAFRUIT Hallowing_M4 Board to setup Platformio. I have createt my own Variant h and cpp Files.
So far the compiling process wirks fine and the upload is error free.

But after the Bootscreen the Board freeze. With my Logic Analyser i have checked the I2C, SPI-Sd and the SPI-LCD connection and every Port seams to work without Problem. I can rad the EEPRM Data and can see the Data from the SD-card.

I have already Repetier2 running on this Board without any problems, but for completness i whould like to get Marlin working.

I even tried Marlin 2.0.5.5, the only difference was the Serial Output stop at a different Message.
Attached is the Output from the Serial Terminal.
The Freeze is exactly 5 seconds aftr power on or reset.

I hope we can communicate about this and finaly fix the problem.
Thank you very much in advance for your patience .

My e-mail: bkkelch1@yahoo.deä
[Serial.log](https://github.com/GMagician/SAMD51-SmartEEprom-Manager/files/4514514/Serial.log)

**Comment by GMagician** [comment]
@Plebejer258 sorry to answer just now..Don't know why but I did not received an email to signal your issue....

During development I faced different freeze causes:
1) i2c with no pullup resistors (if you enabled some devices that use it)
2) no thermistor connected (marlin goes into temperature "protection mode")

**Comment by GMagician** [comment]
From log nothing is helping but 5 seconds delayed freeze sound to me like 2nd point may be right candidate

**Comment by GMagician** [comment]
@Plebejer258 5 seconds may also be watchdog...you may disable it and check where marlin hangs...

**Comment by Plebejer258** [comment]
Good morning Mr. Zaro,

thank you very much for your response. Better late then never.:-))

In the meantime all the problems are fixed.
The main problem was the RTC.
I using the setup of the Adafruit Hallowing_M4 Board and for this Board 
the setup parms in the Boards.txt include 'Crystalless'. This was the 
reason for the freeze.
After this was fixed i was faced with an other problem. No ADC values.
In your ADC setup you defined VREF=External. I have the VREF Pin not 
connected to any voltage.
Now every thing looks good. After my own Board is finished i will test 
Marlin on this Board.

I want give you some details of my Board: SAMD51J19A, 4 replaceable 
Stepper Driver, TMC220x capable, 3 Thermistors, EXP1 + EXP2, Paneldue 
connector, TFT connector, 3 Serial and 2 free Pins for own functions.

If you interested, i can provide you with the  Schematic and Board files 
for Eagle.

Thank you very much for your Help
Regards
Franz Eder


Am 15.05.2020 04:31, schrieb Giuliano Zaro:

**Comment by GMagician** [comment]
Glad to ear you solved all your issues.

On my setup I used as adc vref the voltage supplied by shield by external pin. I may also use internal 3.3v because this is the only voltage allowed by AGCM4 SoC (silicon bug).
Please note that I used RTC timer for temperature ISR (so I can free up a timer for fast pwm), currently a lot of timers are used: 2:stepper (need 32 bits timer), 1:tone, 1:servo, 1:softUART and these timers are also used to generate pwm so more free more fast pwm available.

As HW I'm currently using ramps 1.4.4 and I'm using 5 steppers (X, Y, Z1, Z2, E0). What I see from your board description is lack of some free pins, maybe SoC is smaller than AGCM4 one? I'm thinking of a runout sensor, bltouch, fan...but if you want to give me a pdf with your schematic I may "learn" something new....

**Comment by GMagician** [comment]
@Plebejer258 another thing, Mr Eder, don't use tinyUSB from platformio, original Adafruit code had a bug I fixed some time ago, Adafruit included it but I don't know if platformio did it. The issue it has is that when Marlin sends data via USB, it sends single chars and when buffer is full chars are discarded. This bug is not present in full usb and, as I wrote before, is fixed in Adafruit github source but at time I last checked it, not in platformio

**Comment by Plebejer258** [comment]
Hi,
yes i know the Board is not designed for cover every thing. My goal was to have a Board for the smaller Printer without all the 'nice to have' features. But there is still a Pin for a Runout Sensor and a Pin for the Bedlevel. Anyway, first i must get this Board running under normal conditions to see how it performs. Attached is the Schematic in PDF Format. My you can see some flaws in the Design. I am not a professional Designer but i have done some Shields for DUE with TMC Support.
Up to now i haven't discoverd any problems with USB but i didn't use it very heavy.
[MINISAMD51_v2.pdf](https://github.com/GMagician/SAMD51-SmartEEprom-Manager/files/4633643/MINISAMD51_v2.pdf)

**Comment by GMagician** [comment]
Hi, I'm not an electronic designer, only thing I can suggest, but evaluate with your knowledge:
1) 5V on serial1 & 2 and nothing on rx? your tx signal is 3.3v, not all device tollerate this instead of 5V but for sure if you get 5v on rx you will burn your Soc
2) Consider sensorless homing, it's often used with tmc220x

**Comment by Plebejer258** [comment]
Hi,
thanky you for your response.
Serial 2 is connected to a Jumper for 3 or 5v. Serial 1 has only 5v. The reason is 'Paneldue'. Paneldue generate his own 3 v from 5v input. Also some other TFT's need 5 V but working on the TX Line with 3v.
I'm a Repetier user for a long time and Paneldue is full integrated with this software Marlin still working on this halfhearted for over 1 1/2 year. And my C++ is not good enough to finish the integration.
Sensoreless homing was never an optin for me. I read about so many problems and i can not see any real advantage over physical switches or like i have hall sensor's.
But wait and let see my Board running, maybe there ae other hidden Problems or design flaws.

**Comment by Plebejer258** [comment]
I forgot, your TinyUSB Patch is alread in the Platformio TinyUSB included.

**Comment by GMagician** [comment]
> Marlin still working on this halfhearted for over 1 1/2 year.

yes, true, but I think it's a parked development I suppose

> Sensoreless homing was never an optin for me. I read about so many problems 

that's not good to read, I was planning to use them in my new bear printer...I'll see

**Comment by Plebejer258** [comment]
Hi Mr. Zaro,

i finished my Board now and run the first Test's. But ifaced with a 
strange behavior.
My LCD, Analog Input, Heated Bed, Extruder und Fan's are working. But 
none of the Stepper Driver.
I did try two different Driver one A4988 and one DRV8825. But every 
Driver makes only one short move and the freeze.

Did you test the Grand Central Board with some of this Drivers ?

Every thing is running fine with Repetier Software, also the same Driver.
I hope you have some Idear.
In the Configuration i turned NO_MOVE_WITHOUT_HOMING off.

Regards
F.Eder

Am 16.05.2020 14:45, schrieb Giuliano Zaro:

**Comment by Plebejer258** [comment]
I have reopen'd this communication

**Comment by GMagician** [comment]
Hi @Plebejer258 I'm still building my prusa bear so I made just limited test on steppers. I moved succesfully a nema17 using tmc2209 via serial

**Comment by GMagician** [comment]
@Plebejer258 be sure to use latest bugfix..some weeks ago I changed something on stepper timers to fix some issues

**Comment by Plebejer258** [comment]
Your Timer Patch fixed my Problem.
The Stepper work's now as expected. It looks like every thing works now. I will keep you updated on my progress.
